import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Hola soy GROOT Layout</h1>
        <nav className="navbar">
          NextJs 13 Workshop
          <Link href="/">
            <Image alt="Logo" src="/yoshi.png" width={50} height={50} />
          </Link>
          <div className="">
            <Link href="/users">Users</Link>
          </div>
        </nav>
        <div className="px-4">{children}</div>
      </body>
    </html>
  );
}
