import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>Hola soy ROOT Layout</h1>
        <nav className="navbar">
          NextJs 13 Workshop
          <div className="">
            <Link href="/posts/1">First Post</Link>
            <Link href="/posts/2">Second Post</Link>
            <Link href="/go-catch-em-all/ditto">Catch-em-all Pokémon</Link>
            <Link href="/members">Members</Link>
            <Link href="/error-example">Error example</Link>
            <Link href="/route-handlers">Route handlers</Link>
          </div>
        </nav>
        <div className="px-4">{children}</div>
      </body>
    </html>
  );
}
